/**
 * Mock PR-mon data for local development without a backend.
 * Shapes match exactly what GET /api/prmons returns (see server/prmon.js → prToStats).
 */

export const MOCK_PRMONS = [
  {
    id: 42,
    name: 'BUGFIX-ASAUR',
    level: 7,
    hp: 120,
    maxHp: 120,
    defense: 15,
    attack: 18,
    speed: 38,
    type: { name: 'FIRE', color: '#f08030', badge: '🔥' },
    prTitle: 'fix: resolve null pointer in auth middleware',
    prNumber: 42,
    prUrl: 'https://github.com/octocat/Hello-World/pull/42',
    authorAvatar: 'https://avatars.githubusercontent.com/u/583231',
    authorName: 'octocat',
    additions: 87,
    deletions: 33,
    changedFiles: 3,
    repo: 'octocat/Hello-World',
  },
  {
    id: 108,
    name: 'FEATURE-IZARD',
    level: 25,
    hp: 350,
    maxHp: 350,
    defense: 30,
    attack: 35,
    speed: 20,
    type: { name: 'NORMAL', color: '#a8a878', badge: '⭐' },
    prTitle: 'feat: add dark mode support across all components',
    prNumber: 108,
    prUrl: 'https://github.com/octocat/Hello-World/pull/108',
    authorAvatar: 'https://avatars.githubusercontent.com/u/9919',
    authorName: 'mojombo',
    additions: 245,
    deletions: 105,
    changedFiles: 12,
    repo: 'octocat/Hello-World',
  },
  {
    id: 7,
    name: 'HOTFIX-CHU',
    level: 3,
    hp: 50,
    maxHp: 50,
    defense: 5,
    attack: 12,
    speed: 47,
    type: { name: 'ELECTRIC', color: '#f8d030', badge: '⚡' },
    prTitle: 'hotfix: patch XSS vulnerability in search input',
    prNumber: 7,
    prUrl: 'https://github.com/octocat/Hello-World/pull/7',
    authorAvatar: 'https://avatars.githubusercontent.com/u/2',
    authorName: 'defunkt',
    additions: 30,
    deletions: 20,
    changedFiles: 1,
    repo: 'octocat/Hello-World',
  },
  {
    id: 256,
    name: 'REFACTOR-DOS',
    level: 40,
    hp: 500,
    maxHp: 500,
    defense: 50,
    attack: 40,
    speed: 5,
    type: { name: 'GHOST', color: '#705898', badge: '👻' },
    prTitle: 'refactor: rewrite entire ORM layer to use query builder',
    prNumber: 256,
    prUrl: 'https://github.com/octocat/Hello-World/pull/256',
    authorAvatar: 'https://avatars.githubusercontent.com/u/1',
    authorName: 'torvalds',
    additions: 412,
    deletions: 88,
    changedFiles: 24,
    repo: 'octocat/Hello-World',
  },
];
